---
name: Feature request
description: Use this to request new features.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting new feature for the project.

        Please be aware that the best way to get your feature implemented as fast as
        possible is by submitting Pull Request.
  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: |
        Please search issues in this repository and
        [PyPlumIO](https://github.com/denpamusic/PyPlumIO/issues) repository to
        see if an issue already exists for the bug you've encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: "I want to suggest:"
      description: Please select what type of feature you want implemented?
      options:
        - label: support for a new product
        - label: new functionality for a product
        - label: documentation improvement
        - label: other
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Feature description"
      description: Describe a feature that you want to suggest with as much detail as you can.
    validations:
      required: true
  - type: input
    attributes:
      label: "Webpage of the product, that I'm suggesting:"
      description: |
        If you're suggesting support for a new product, please provide URL
        pointing to a product page on Plum's website.
      placeholder: "https://www.plum.pl/en/project/..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "My diagnostics data:"
      description: |
        Please paste or drag & drop your diagnostics data here.

        Tip: You can learn more about diagnostics
        [here](https://www.home-assistant.io/integrations/diagnostics/).
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/denpamusic/homeassistant-plum-ecomax/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
