"""Constants for the Plum ecoMAX integration."""

DOMAIN = "plum_ecomax"

DEFAULT_PORT = 8899
UPDATE_INTERVAL = 10
CONNECTION_CHECK_TRIES = 5

FLOW_KGH = "kg/h"

ECOMAX_STATE_OFF = 0
ECOMAX_STATE_PRIORITY = 1
ECOMAX_STATE_NORMAL = 2
